services:
  combined_app:
    build: .
    ports:
      - "8000:8000"
      - "8090:8090"
    volumes:
      - ./pb_migrations:/pb_migrations
      - ./CSV:/app/CSV
    env_file:
      - .env
    environment:
      - POCKETBASE_URL=http://localhost:8090
volumes:
  pocketbase_data: