services:
  combined_app:
    build: .
    ports:
      - "8000:8000"
      - "8090:8090"
    volumes:
      - .:/app
      - pocketbase_data:/pb_data
      - ./pb_migrations:/pb_migrations
    environment:
      - POCKETBASE_URL=http://localhost:8090
volumes:
  pocketbase_data: